server:
  port: 8081

#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none


logging:
  level:
    org.springframework: DEBUG